name: agora_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.2.6
  permission_handler: ^9.2.0
  http: ^0.13.5
  image: ^4.1.3
  path: 1.8.3
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
